api/urls.py
from django.urls import path
import api.views as views

app_name = 'api'

urlpatterns = [
    path('', views.Model_Predict.as_view(), name='predict'),
]

app/urls.py
from django.urls import path
import app.views as views

app_name = 'app'

urlpatterns = [
    path('', views.model_form, name='model_form'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from .apps import ModelConfig
import pandas as pd


class Model_Predict(APIView):
    def post(self, request, format=None):
        try:
            # If request is made directly to api this code will execute
            if type(request.data) is dict:
                data = request.data

            # If request is made through frontend code will execute
            else:
                data = request.data
                data = data.dict()
                data.pop('csrfmiddlewaretoken')
            keys = []
            values = []
            # Values are seperated from keys and placed in array
            for key in data:
                keys.append(key)
                values.append(int(data[key]))
            # Array is reshaped and then passed to model
            X = pd.Series(values).to_numpy().reshape(1, -1)
            loaded_classifier = ModelConfig.classifier
            y_pred = loaded_classifier.predict(X)
            # Model response is 0 or 1 that response is then made
            # human readable via target map
            y_pred = pd.Series(y_pred)
            target_map = {0: 'rejected', 1: 'approved'}
            # Target is mapped below
            y_pred = y_pred.map(target_map).to_numpy()
            # Response is created and returns dictionary
            response_dict = {"prediction": f"{y_pred[0]}"}
            return Response(response_dict, status=200)
        except ValueError as error:
            return (error.args[0], status.HTTP_400_BAD_REQUEST)

app/views.py
from django.shortcuts import render
from django.contrib import messages


def model_form(request):
    return render(request, 'app/model_form.html')

# def template_example_1(request):
#     return render(request,"child_page_1.html")

app/templates/app/base_template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            {% block title %}{% endblock title %}
        </title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css">
        <link rel='stylesheet' href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="https://stanneschurch.co.za/wp-content/uploads/portolio-assets/style.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        {% block body_data %}{% endblock body_data %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/additional-methods.js" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js" defer></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" defer></script>
        <script src="https://stanneschurch.co.za/wp-content/uploads/portolio-assets/script.js"></script>
    </body>
</html>

app/templates/app/model_form.html
{% extends 'app/base_template.html' %}

{% block title %}
Loan Prediction Model Form
{% endblock title %}

{% block body_data %}
        <!-- Multi step form -->
        <section class="multi_step_form">

            <form action="{% url 'api:predict' %}" method="POST" id="msform" class="form_style">
                {% csrf_token %}
                <!-- title -->
                <div class="title">
                    <h2>Bank Loan Approval</h2>
                    <p>Fill in your details below to check if you would be eligible for a loan</p>
                </div>
                <!-- progressbar -->
                <ul id="progressbar">
                    <li class="active">Personal Info</li>
                    <li>Loan Info</li>
                    <li>Prediction</li>
                </ul>
                <!-- fieldsets -->
                <fieldset id="personal_info">
                    <h3>Personal Information</h3>
                    <h6>Please fill in your personal details.</h6>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_applicant_income">Select Gender:</label>
                                <div class="loan_input">
                                    <select name="gender" id="id_gender" class="product_select">
                                        <option value="1" data-display="Male">Male</option>
                                        <option value="0">Female</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_married">Select Marital Status:</label>
                                <div class="loan_input">
                                    <select name="married" id="id_married" class="product_select">
                                        <option value="1" data-display="Married">Married</option>
                                        <option value="0">Not married</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4 mb-3">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_dependents">Select Number of Dependents:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" placeholder="Enter Number of Dependents" name="dependents" id="id_dependents">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_education">Education Level:</label>
                                <div class="loan_input">
                                    <select name="education" id="id_education" class="product_select">
                                        <option value="1" data-display="Graduate">Graduate</option>
                                        <option value="0">Not graduated</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_self_employed">Self employed:</label>
                                <div class="loan_input">
                                    <select name="self_employed" id="id_self_employed" class="product_select">
                                        <option value="1">Yes</option>
                                        <option value="0">No</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_property_area">Property area:</label>
                                <div class="loan_input">
                                    <select name="property_area" id="id_property_area" class="product_select">
                                        <option value="0" data-display="Rural">Rural</option>
                                        <option value="1">Semiurban</option>
                                        <option value="2">Urban</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="next action-button">Continue</button>
                </fieldset>


                <fieldset id="loan_info">
                    <h3>Loan Information</h3>
                    <h6>Please fill in your relevant loan and financial information.</h6>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_applicant_income">Applicant Income:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="applicant_income" placeholder="Enter Monthly Gross Income"  id="id_applicant_income">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_coapplicant_income">Coapplicant Income:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="coapplicant_income" placeholder="Enter Co-Applicant Monthly Gross Income" id="id_coapplicant_income">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-2 mb-2">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_loan_amount">Loan Amount:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="loan_amount" placeholder="Requested Loan Amount" id="id_loan_amount">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_loan_amount_term">Loan Amount Term:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="loan_amount_term" placeholder="Loan Term in Months" id="id_loan_amount_term">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="id_credit_history">Credit history:</label>
                                <div class="loan_input">
                                    <select name="credit_history" id="id_credit_history" class="product_select">
                                        <option value="0" data-display="Blacklisted">Blacklisted</option>
                                        <option value="1">Decent</option>
                                        <option value="2">Good</option>
                                        <option value="3">Great</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="button" class="action-button previous previous_button">Back</button>
                    <button type="submit" class="submit action-button" data-target="#prediction">Submit</button>
                </fieldset>


                <fieldset id="prediction">
                    <h3>Prediction</h3>
                    <h6>Below is your loan status prediction according to our machine learning model</h6>
                    <div class="done_text">
                        <div id="response_loading"></div>
                        <div id="response_dict"></div>
                    </div>

                    <button type="button" class="action-button reload previous_button">Reload and Try Again?</button>
                    <a href="https://github.com/Evan031/bankloan-approval" target="_blank" class="action-button github_link">View Source Code</a>
                </fieldset>
            </form>
        </section>
        <!-- End Multi step form -->
{% endblock body_data %}

app/templates/myform/model-form.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Loan Approval Web Application</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css">
        <link rel='stylesheet' href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
        <!-- Multi step form -->
        <section class="multi_step_form">

            <form action="{% url 'api:predict' %}" method="POST" id="msform" class="form_style">
                {% csrf_token %}
                <!-- title -->
                <div class="title">
                    <h2>Bank Loan Approval</h2>
                    <p>Fill in your details below to check if you would be eligible for a loan</p>
                </div>
                <!-- progressbar -->
                <ul id="progressbar">
                    <li class="active">Personal Info</li>
                    <li>Loan Info</li>
                    <li>Prediction</li>
                </ul>
                <!-- fieldsets -->
                <fieldset id="personal_info">
                    <h3>Personal Information</h3>
                    <h6>Please fill in your personal details.</h6>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_applicant_income">Select Gender:</label>
                                <div class="loan_input">
                                    <select name="gender" id="id_gender" class="product_select">
                                        <option value="1" data-display="Male">Male</option>
                                        <option value="0">Female</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_married">Select Marital Status:</label>
                                <div class="loan_input">
                                    <select name="married" id="id_married" class="product_select">
                                        <option value="1" data-display="Married">Married</option>
                                        <option value="0">Not married</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4 mb-3">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_dependents">Select Number of Dependents:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" placeholder="Enter Number of Dependents" name="dependents" id="id_dependents">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_education">Education Level:</label>
                                <div class="loan_input">
                                    <select name="education" id="id_education" class="product_select">
                                        <option value="1" data-display="Graduate">Graduate</option>
                                        <option value="0">Not graduated</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_self_employed">Self employed:</label>
                                <div class="loan_input">
                                    <select name="self_employed" id="id_self_employed" class="product_select">
                                        <option value="1">Yes</option>
                                        <option value="0">No</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_property_area">Property area:</label>
                                <div class="loan_input">
                                    <select name="property_area" id="id_property_area" class="product_select">
                                        <option value="0" data-display="Rural">Rural</option>
                                        <option value="1">Semiurban</option>
                                        <option value="2">Urban</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="next action-button">Continue</button>
                </fieldset>


                <fieldset id="loan_info">
                    <h3>Loan Information</h3>
                    <h6>Please fill in your relevant loan and financial information.</h6>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_applicant_income">Applicant Income:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="applicant_income" placeholder="Enter Monthly Gross Income"  id="id_applicant_income">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_coapplicant_income">Coapplicant Income:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="coapplicant_income" placeholder="Enter Co-Applicant Monthly Gross Income" id="id_coapplicant_income">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-2 mb-2">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_loan_amount">Loan Amount:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="loan_amount" placeholder="Requested Loan Amount" id="id_loan_amount">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="id_loan_amount_term">Loan Amount Term:</label>
                                <div class="loan_input">
                                    <input type="number" class="form-control" name="loan_amount_term" placeholder="Loan Term in Months" id="id_loan_amount_term">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="id_credit_history">Credit history:</label>
                                <div class="loan_input">
                                    <select name="credit_history" id="id_credit_history" class="product_select">
                                        <option value="0" data-display="Blacklisted">Blacklisted</option>
                                        <option value="1">Decent</option>
                                        <option value="2">Good</option>
                                        <option value="3">Great</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="button" class="action-button previous previous_button">Back</button>
                    <button type="submit" class="submit action-button" data-target="#prediction">Submit</button>
                </fieldset>


                <fieldset id="prediction">
                    <h3>Prediction</h3>
                    <h6>Below is your loan status prediction according to our machine learning model</h6>
                    <div class="done_text">
                        <div id="response_loading"></div>
                        <div id="response_dict"></div>
                    </div>

                    <button type="button" class="action-button reload previous_button">Reload and Try Again?</button>
                    <a href="https://github.com/Evan031/bankloan-approval" target="_blank" class="action-button github_link">View Source Code</a>
                </fieldset>
            </form>
        </section>
        <!-- End Multi step form -->

    </body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" defer></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js" defer></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/additional-methods.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js" defer></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" defer></script>
    <script src="{% static 'app/js/script.js' %}"></script>

</html>